const areaCode1 = [
  { name: "전국", num: 0 },
  { name: "서울", num: 1 },
  { name: "인천", num: 2 },
  { name: "대전", num: 3 },
  { name: "대구", num: 4 },
  { name: "광주", num: 5 },
  { name: "부산", num: 6 },
  { name: "울산", num: 7 },
  { name: "세종특별자치시", num: 9 },
  { name: "경기도", num: 31 },
  { name: "강원특별자치도", num: 32 },
  { name: "충청북도", num: 33 },
  { name: "충청남도", num: 34 },
  { name: "경상북도", num: 35 },
  { name: "경상남도", num: 36 },
  { name: "전라북도", num: 37 },
  { name: "전라남도", num: 38 },
  { name: "제주도", num: 39 },
];
export default areaCode1;
