const areaCode2 = {
  0: [{ name: ' ', num: 0, areaCode1: 0 }],
  1: [
    { name: '강남구', num: 1, areaCode1: 1 },
    { name: '강동구', num: 2, areaCode1: 1 },
    { name: '강북구', num: 3, areaCode1: 1 },
    { name: '강서구', num: 4, areaCode1: 1 },
    { name: '관악구', num: 5, areaCode1: 1 },
    { name: '광진구', num: 6, areaCode1: 1 },
    { name: '구로구', num: 7, areaCode1: 1 },
    { name: '금천구', num: 8, areaCode1: 1 },
    { name: '노원구', num: 9, areaCode1: 1 },
    { name: '도봉구', num: 10, areaCode1: 1 },
    { name: '동대문구', num: 11, areaCode1: 1 },
    { name: '동작구', num: 12, areaCode1: 1 },
    { name: '마포구', num: 13, areaCode1: 1 },
    { name: '서대문구', num: 14, areaCode1: 1 },
    { name: '서초구', num: 15, areaCode1: 1 },
    { name: '성동구', num: 16, areaCode1: 1 },
    { name: '성북구', num: 17, areaCode1: 1 },
    { name: '송파구', num: 18, areaCode1: 1 },
    { name: '양천구', num: 19, areaCode1: 1 },
    { name: '영등포구', num: 20, areaCode1: 1 },
    { name: '용산구', num: 21, areaCode1: 1 },
    { name: '은평구', num: 22, areaCode1: 1 },
    { name: '종로구', num: 23, areaCode1: 1 },
    { name: '중구', num: 24, areaCode1: 1 },
    { name: '중랑구', num: 25, areaCode1: 1 },
  ],
  2: [
    { name: '강화군', num: 1, areaCode1: 2 },
    { name: '계양구', num: 2, areaCode1: 2 },
    { name: '미추홀구', num: 3, areaCode1: 2 },
    { name: '남동구', num: 4, areaCode1: 2 },
    { name: '동구', num: 5, areaCode1: 2 },
    { name: '부평구', num: 6, areaCode1: 2 },
    { name: '서구', num: 7, areaCode1: 2 },
    { name: '연수구', num: 8, areaCode1: 2 },
    { name: '옹진군', num: 9, areaCode1: 2 },
    { name: '중구', num: 10, areaCode1: 2 },
  ],
  3: [
    { name: '대덕구', num: 1, areaCode1: 3 },
    { name: '동구', num: 2, areaCode1: 3 },
    { name: '서구', num: 3, areaCode1: 3 },
    { name: '유성구', num: 4, areaCode1: 3 },
    { name: '중구', num: 5, areaCode1: 3 },
  ],
  4: [
    { name: '남구', num: 1, areaCode1: 4 },
    { name: '달서구', num: 2, areaCode1: 4 },
    { name: '달성군', num: 3, areaCode1: 4 },
    { name: '동구', num: 4, areaCode1: 4 },
    { name: '북구', num: 5, areaCode1: 4 },
    { name: '서구', num: 6, areaCode1: 4 },
    { name: '수성구', num: 7, areaCode1: 4 },
    { name: '중구', num: 8, areaCode1: 4 },
    { name: '군위군', num: 9, areaCode1: 4 },
  ],
  5: [
    { name: '광산구', num: 1, areaCode1: 5 },
    { name: '남구', num: 2, areaCode1: 5 },
    { name: '동구', num: 3, areaCode1: 5 },
    { name: '북구', num: 4, areaCode1: 5 },
    { name: '서구', num: 5, areaCode1: 5 },
  ],
  6: [
    { name: '강서구', num: 1, areaCode1: 6 },
    { name: '금정구', num: 2, areaCode1: 6 },
    { name: '기장군', num: 3, areaCode1: 6 },
    { name: '남구', num: 4, areaCode1: 6 },
    { name: '동구', num: 5, areaCode1: 6 },
    { name: '동래구', num: 6, areaCode1: 6 },
    { name: '부산진구', num: 7, areaCode1: 6 },
    { name: '북구', num: 8, areaCode1: 6 },
    { name: '사상구', num: 9, areaCode1: 6 },
    { name: '사하구', num: 10, areaCode1: 6 },
    { name: '서구', num: 11, areaCode1: 6 },
    { name: '수영구', num: 12, areaCode1: 6 },
    { name: '연제구', num: 13, areaCode1: 6 },
    { name: '영도구', num: 14, areaCode1: 6 },
    { name: '중구', num: 15, areaCode1: 6 },
    { name: '해운대구', num: 16, areaCode1: 6 },
  ],
  7: [
    { name: '중구', num: 1, areaCode1: 7 },
    { name: '남구', num: 2, areaCode1: 7 },
    { name: '동구', num: 3, areaCode1: 7 },
    { name: '북구', num: 4, areaCode1: 7 },
    { name: '울주군', num: 5, areaCode1: 7 },
  ],
  8: [{ name: '세종특별자치시', num: 1, areaCode1: 8 }],
  31: [
    { name: '가평군', num: 1, areaCode1: 31 },
    { name: '고양시', num: 2, areaCode1: 31 },
    { name: '과천시', num: 3, areaCode1: 31 },
    { name: '광명시', num: 4, areaCode1: 31 },
    { name: '광주시', num: 5, areaCode1: 31 },
    { name: '구리시', num: 6, areaCode1: 31 },
    { name: '군포시', num: 7, areaCode1: 31 },
    { name: '김포시', num: 8, areaCode1: 31 },
    { name: '남양주시', num: 9, areaCode1: 31 },
    { name: '동두천시', num: 10, areaCode1: 31 },
    { name: '부천시', num: 11, areaCode1: 31 },
    { name: '성남시', num: 12, areaCode1: 31 },
    { name: '수원시', num: 13, areaCode1: 31 },
    { name: '시흥시', num: 14, areaCode1: 31 },
    { name: '안산시', num: 15, areaCode1: 31 },
    { name: '안성시', num: 16, areaCode1: 31 },
    { name: '안양시', num: 17, areaCode1: 31 },
    { name: '양주시', num: 18, areaCode1: 31 },
    { name: '양평군', num: 19, areaCode1: 31 },
    { name: '여주시', num: 20, areaCode1: 31 },
    { name: '연천군', num: 21, areaCode1: 31 },
    { name: '오산시', num: 22, areaCode1: 31 },
    { name: '용인시', num: 23, areaCode1: 31 },
    { name: '의왕시', num: 24, areaCode1: 31 },
    { name: '의정부시', num: 25, areaCode1: 31 },
    { name: '이천시', num: 26, areaCode1: 31 },
    { name: '파주시', num: 27, areaCode1: 31 },
    { name: '평택시', num: 28, areaCode1: 31 },
    { name: '포천시', num: 29, areaCode1: 31 },
    { name: '하남시', num: 30, areaCode1: 31 },
    { name: '화성시', num: 31, areaCode1: 31 },
  ],
  32: [
    { name: '강릉시', num: 1, areaCode1: 32 },
    { name: '고성군', num: 2, areaCode1: 32 },
    { name: '동해시', num: 3, areaCode1: 32 },
    { name: '삼척시', num: 4, areaCode1: 32 },
    { name: '속초시', num: 5, areaCode1: 32 },
    { name: '양구군', num: 6, areaCode1: 32 },
    { name: '양양군', num: 7, areaCode1: 32 },
    { name: '영월군', num: 8, areaCode1: 32 },
    { name: '원주시', num: 9, areaCode1: 32 },
    { name: '인제군', num: 10, areaCode1: 32 },
    { name: '정선군', num: 11, areaCode1: 32 },
    { name: '철원군', num: 12, areaCode1: 32 },
    { name: '춘천시', num: 13, areaCode1: 32 },
    { name: '태백시', num: 14, areaCode1: 32 },
    { name: '평창군', num: 15, areaCode1: 32 },
    { name: '홍천군', num: 16, areaCode1: 32 },
    { name: '화천군', num: 17, areaCode1: 32 },
    { name: '횡성군', num: 18, areaCode1: 32 },
  ],
  33: [
    { name: '괴산군', num: 1, areaCode1: 33 },
    { name: '단양군', num: 2, areaCode1: 33 },
    { name: '보은군', num: 3, areaCode1: 33 },
    { name: '영동군', num: 4, areaCode1: 33 },
    { name: '옥천군', num: 5, areaCode1: 33 },
    { name: '음성군', num: 6, areaCode1: 33 },
    { name: '제천시', num: 7, areaCode1: 33 },
    { name: '진천군', num: 8, areaCode1: 33 },
    { name: '청원군', num: 9, areaCode1: 33 },
    { name: '청주시', num: 10, areaCode1: 33 },
    { name: '충주시', num: 11, areaCode1: 33 },
    { name: '증평군', num: 12, areaCode1: 33 },
  ],
  34: [
    { name: '공주시', num: 1, areaCode1: 34 },
    { name: '금산군', num: 2, areaCode1: 34 },
    { name: '논산시', num: 3, areaCode1: 34 },
    { name: '당진시', num: 4, areaCode1: 34 },
    { name: '보령시', num: 5, areaCode1: 34 },
    { name: '부여군', num: 6, areaCode1: 34 },
    { name: '서산시', num: 7, areaCode1: 34 },
    { name: '서천군', num: 8, areaCode1: 34 },
    { name: '아산시', num: 9, areaCode1: 34 },
    { name: '예산군', num: 11, areaCode1: 34 },
    { name: '천안시', num: 12, areaCode1: 34 },
    { name: '청양군', num: 13, areaCode1: 34 },
    { name: '태안군', num: 14, areaCode1: 34 },
    { name: '홍성군', num: 15, areaCode1: 34 },
    { name: '계룡시', num: 16, areaCode1: 34 },
  ],
  35: [
    { name: '경산시', num: 1, areaCode1: 35 },
    { name: '경주시', num: 2, areaCode1: 35 },
    { name: '고령군', num: 3, areaCode1: 35 },
    { name: '구미시', num: 4, areaCode1: 35 },
    { name: '김천시', num: 6, areaCode1: 35 },
    { name: '문경시', num: 7, areaCode1: 35 },
    { name: '봉화군', num: 8, areaCode1: 35 },
    { name: '상주시', num: 9, areaCode1: 35 },
    { name: '성주군', num: 10, areaCode1: 35 },
    { name: '안동시', num: 11, areaCode1: 35 },
    { name: '영덕군', num: 12, areaCode1: 35 },
    { name: '영양군', num: 13, areaCode1: 35 },
    { name: '영주시', num: 14, areaCode1: 35 },
    { name: '영천시', num: 15, areaCode1: 35 },
    { name: '예천군', num: 16, areaCode1: 35 },
    { name: '울릉군', num: 17, areaCode1: 35 },
    { name: '울진군', num: 18, areaCode1: 35 },
    { name: '의성군', num: 19, areaCode1: 35 },
    { name: '청도군', num: 20, areaCode1: 35 },
    { name: '청송군', num: 21, areaCode1: 35 },
    { name: '칠곡군', num: 22, areaCode1: 35 },
    { name: '포항시', num: 23, areaCode1: 35 },
  ],
  36: [
    { name: '거제시', num: 1, areaCode1: 36 },
    { name: '거창군', num: 2, areaCode1: 36 },
    { name: '고성군', num: 3, areaCode1: 36 },
    { name: '김해시', num: 4, areaCode1: 36 },
    { name: '남해군', num: 5, areaCode1: 36 },
    { name: '마산시', num: 6, areaCode1: 36 },
    { name: '밀양시', num: 7, areaCode1: 36 },
    { name: '사천시', num: 8, areaCode1: 36 },
    { name: '산청군', num: 9, areaCode1: 36 },
    { name: '양산시', num: 10, areaCode1: 36 },
    { name: '의령군', num: 12, areaCode1: 36 },
    { name: '진주시', num: 13, areaCode1: 36 },
    { name: '진해시', num: 14, areaCode1: 36 },
    { name: '창녕군', num: 15, areaCode1: 36 },
    { name: '창원시', num: 16, areaCode1: 36 },
    { name: '통영시', num: 17, areaCode1: 36 },
    { name: '하동군', num: 18, areaCode1: 36 },
    { name: '함안군', num: 19, areaCode1: 36 },
    { name: '함양군', num: 20, areaCode1: 36 },
    { name: '합천군', num: 21, areaCode1: 36 },
  ],
  37: [
    { name: '고창군', num: 1, areaCode1: 37 },
    { name: '군산시', num: 2, areaCode1: 37 },
    { name: '김제시', num: 3, areaCode1: 37 },
    { name: '남원시', num: 4, areaCode1: 37 },
    { name: '무주군', num: 5, areaCode1: 37 },
    { name: '부안군', num: 6, areaCode1: 37 },
    { name: '순창군', num: 7, areaCode1: 37 },
    { name: '완주군', num: 8, areaCode1: 37 },
    { name: '익산시', num: 9, areaCode1: 37 },
    { name: '임실군', num: 10, areaCode1: 37 },
    { name: '장수군', num: 11, areaCode1: 37 },
    { name: '전주시', num: 12, areaCode1: 37 },
    { name: '정읍시', num: 13, areaCode1: 37 },
    { name: '진안군', num: 14, areaCode1: 37 },
  ],
  38: [
    { name: '강진군', num: 1, areaCode1: 38 },
    { name: '고흥군', num: 2, areaCode1: 38 },
    { name: '곡성군', num: 3, areaCode1: 38 },
    { name: '광양시', num: 4, areaCode1: 38 },
    { name: '구례군', num: 5, areaCode1: 38 },
    { name: '나주시', num: 6, areaCode1: 38 },
    { name: '담양군', num: 7, areaCode1: 38 },
    { name: '목포시', num: 8, areaCode1: 38 },
    { name: '무안군', num: 9, areaCode1: 38 },
    { name: '보성군', num: 10, areaCode1: 38 },
    { name: '순천시', num: 11, areaCode1: 38 },
    { name: '신안군', num: 12, areaCode1: 38 },
    { name: '여수시', num: 13, areaCode1: 38 },
    { name: '영광군', num: 16, areaCode1: 38 },
    { name: '영암군', num: 17, areaCode1: 38 },
    { name: '완도군', num: 18, areaCode1: 38 },
    { name: '장성군', num: 19, areaCode1: 38 },
    { name: '장흥군', num: 20, areaCode1: 38 },
    { name: '진도군', num: 21, areaCode1: 38 },
    { name: '함평군', num: 22, areaCode1: 38 },
    { name: '해남군', num: 23, areaCode1: 38 },
    { name: '화순군', num: 24, areaCode1: 38 },
  ],
  39: [
    { name: '남제주군', num: 1, areaCode1: 39 },
    { name: '북제주군', num: 2, areaCode1: 39 },
    { name: '서귀포시', num: 3, areaCode1: 39 },
    { name: '제주시', num: 4, areaCode1: 39 },
  ],
};

export default areaCode2;
